version: "3.7"

networks:
  generic:
    driver: bridge

services:
  postgres:
    networks:
      - generic
    image:  "postgres:14.3-alpine"
    environment:
      POSTGRES_DB:  generics
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "icash", "-d", "icash"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"

  ominidb:
    networks:
      - generic
    image: "taivokasper/omnidb"
    ports:
      - "8090:8080"